### PR TITLE
YUI docs down to end

### PR DESCRIPTION
**Pull request by SteveMcArthur**
Down to end

### CODE REVIEW

**Comment by SteveMcArthur** [comment]
@balupton how does this look?

**Comment by SteveMcArthur** [comment]
I wonder if we can extract the documentation into the README.md so that it appears on NPM?

**Comment by balupton** [comment]
I've added a link to the docs to the readme, and published a new release :)

**Comment by balupton** [comment]
Just noticed that the documentation for the arguments that the completion callback is probably incorrect, as it looks like they are properties of the function, rather than arguments it receives.

**Pull request merged**
